apiVersion: 1

datasources:
  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://host.docker.internal:3101
    isDefault: true
    jsonData:
      maxLines: 1000
    editable: false
